### ISSUE TITLE
Re-organize source code

### ISSUE THREAD

**Issue by jrasch** [Inedo/upack#33]
The source code for this project should follow this structure from the repository root:

```
/src/dotnet/
  - upack.sln
  -upack.nuspec
  -upack/*.cs
/src/go/*.go
.gitattributes	
.gitignore
LICENSE
README.md
VERIFICATION.md
```

**Comment by BenLubar** [comment]
That would make the Go install command become `go get github.com/inedo/upack/src/go` and install a command named `go`. That's probably not good.

**Comment by jrasch** [comment]
The formatting on that original post is messed up, so I will fix that. Anyway, I have no idea how Go works, would putting the files in `/upack/src/go/upack/` change something, or is there a different command that solves this? Whatever we do, we should not have the files in the root of the repository like there are now.

**Comment by BenLubar** [comment]
We could put most of the files in `/upack/src/go/upack/` and then have a Go file in the repo root that just runs the program, like this:

```
package main

import "github.com/Inedo/upack/src/go/upack"

func main() {
    upack.Main()
}
```

That way, `go get github.com/inedo/upack` would work and the root of the repo wouldn't include anything more than a link to the source code.

We can also add a comment before the `package main` line to have documentation that shows up in places like https://godoc.org/github.com/Inedo/upack.
