### ISSUE TITLE
Install if not already installed

### ISSUE THREAD

**Issue by dazinator** [Inedo/upack#40]
At the moment if you install a package to a target directory:

```
upack install $packageName $packageVersion --source=$feedUrl --target="$targetDir" --user=api:$apiKey
```

It installs.

Suppose you want to do this again idempotently: i.e install the package only if it doesn't already exist. The second time we run the same command, it fails with an exception:

```
Installing Foo to E:\Apps\Foo\1.0.0 
September 27th 2018 11:21:59Error
Unhandled Exception: System.IO.IOException: The file 'E:\Apps\Foo\1.0.0\foo.txt' already exists. 
September 27th 2018 11:21:59Error
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 

```

It would be nice if there was some flags / options available for these scenarios:

1. Force overwrite of the existing package
2. Skip install completely if the package already exists (don't error)

At the moment, the workaround I am using for this (not sure how reliable this is) is:

1. Check if a matching folder exists int he target directory - if it does assume the package has already been installed and therefore don't run the `upack install` command.

**Comment by BenLubar** [comment]
Assuming you only install each package in one place per machine, `upack list` can tell you what version of the package is installed.

**Comment by dazinator** [comment]
How would I consume `upack list` in a powershell or bat script to determine if a package was installed already in a certain location before calling `upack install`? The script would have to call `upack liat` and capture the STDOUT and do some kind of regex match on it? Seems not nice from an API perspective. 

Nuget provides a nuget restore operation which installs packages if not already present, but wont error if yoi call it multiple times as its idempotent. I'm looking for the same kind of semantics if possible.

**Comment by apapadimoulis** [comment]
@dazinator the `install` command has an `--overwrite` flag. What do you think about using it?

Generally speaking, I'd love to get your feedback on Romp, particularly with how the commandline arguments etc:
 * Usage: https://inedo.com/support/documentation/romp/using/creating-publishing
 * CLI: https://inedo.com/support/documentation/romp/command-line/command-overview

Romp has a few more options, particularly things like "validate". We're considering a major new version to upack that implements package sources, and allows upgrades, etc.

**Comment by dazinator** [comment]
I think the overwrite option in case you want to force package re-install. However if the packages are identical i am not sure what the benefit would be of overwrite. Or is it for installing a newer version over an older version at the same path?

Overwrite is useful, but the semantics I am after are install if not already installed. Always installing with overwrite option is doing unnecessary work if the package with the desired version is already installed.

I haven't looked at romp yet, will have a look!

**Comment by steffen-wilke** [comment]
I also think that the CLT should handle already existing files more gracefully. Maybe it can check whether the file from the package is newer and overwrite it in these cases by default. The `--overwrite` flag certainly helps but I don't think that it's the prettiest solution to just overwrite everything although only some files might have changed.

**Comment by apxltd** [comment]
I *think* we can handle this with the upcoming update command  #57  -- what do you think?
