### ISSUE TITLE
Allow single file as source argument for the pack command

### ISSUE THREAD

**Issue by wldevries** [Inedo/upack#44]
The documentation for `pack` mentions that you need to add an entire directory as the contents for a new upack. This is logical, because the tool needs to know what the root directory of the contents should be.

It would be great if `pack` would also accept a single file as `source` argument. The use-case for us would be to make it easy to create a build dependency package containing for instance the .NET platform (`NDP461-KB3102436-x86-x64-AllOS-ENU.exe`) or the XNA redistributable (`xnafx40_redist.msi`).

**Comment by apapadimoulis** [comment]
Just to clarify. 

Do you mean changing this...

`source - Directory containing files to add to the package.`

to

`source - Directory containing files to add to the package, or the single file that will be packaged`

**Comment by wldevries** [comment]
Yes that's exactly what I was thinking of. Usage of wildcards (e.g. `*.jpg`) to include multiple files would be even more powerful.

**Comment by apapadimoulis** [comment]
@BenLubar can you also update docs?

**Comment by BenLubar** [comment]
Are we processing the wildcards ourself (so the command would be `upack pack '*.jpg'`) or are we letting the shell process wildcards and accepting multiple inputs?

How do we distinguish a wildcard that matches 1 directory from the existing way it works?

**Comment by apxltd** [comment]
Hmm, right, Wildcards get complex cross-platform.

let's pass on wild cards now, and just have it be a single file.

`source - Directory containing files to add to the package, or the single file that will be packaged`
