### ISSUE TITLE
Source user and feed arguments from environment variables

### ISSUE THREAD

**Issue by wldevries** [Inedo/upack#45]
When you use the upack program a lot it's quite a hassle to always pass in the feed and user arguments. It would be great if they could be sourced from `UPACK_FEED` and `UPACK_USER`. This would also make it easier to create parameterised build scripts that use upack.

**Comment by apapadimoulis** [comment]
So, Romp has the concept of Package Sources (one of which can be marked as the default):
https://inedo.com/support/documentation/romp/command-line/command-overview/package-sources

I was thinking of having us add this to UPack, too. How do you think?

**Comment by wldevries** [comment]
That would be very useful! It doesn't really fit with our Jenkins set-up, but I get where you're coming from :-)

**Comment by gdivis** [comment]
Just added support for defaulting to those environment variables in v2.2.4. Hope this helps!
