### ISSUE TITLE
OutOfMemoryException when installing big packages

### ISSUE THREAD

**Issue by skovsende** [Inedo/upack#46]
I have a 1GB package that I try to install with

```
upack.exe install MyPackage --source=http://internal-package-feed/feed-location/ --target="c:/temp"
```

Using upack 2.2.2

**Comment by skovsende** [comment]
@gdivis - Any idea when upack.exe get's updated to use the latest version of Inedo.Upack? I will happily make a PR if you'll accept it :)

**Comment by gdivis** [comment]
@skovsende Just updated it. We'll get an updated .exe built & pushed shortly. Thanks!

**Comment by skovsende** [comment]
Any news on when a new release will be made?

**Comment by gdivis** [comment]
Release was just published now.
