### ISSUE TITLE
'upack.exe push' hangs with v2.2.3.9

### ISSUE THREAD

**Issue by dieterv** [Inedo/upack#49]
Originally asked for help on the support forums: https://inedo.com/support/questions/9637

To recap, upack.exe 2.2.3.9 hangs when pushing to a universal feed:
```
upack.exe --version
upack 2.2.3.9
Usage: upack «command»
<snip>

upack.exe push "C:/Path/To/TestApplication-0.1.0.upack" "http://proget.mycompany.local:8000/upack/Test-Packages" --user=api:[RedactedMySuperSecretApiKey]
Package: MyCompany/Sandbox/TestApplication
Version: 0.1.0-ci.33
^C   # Blocks here so I eventually cancel the command...
```

Using upack.exe 2.2.2.2 pushing works correctly:
```
upack.exe" --version
upack 2.2.2.2
Usage: upack «command»
<snip>

upack.exe push "C:/Path/To/TestApplication-0.1.0.upack" "http://proget.mycompany.local:8000/upack/Test-Packages" --user=api:[RedactedMySuperSecretApiKey]
Package: MyCompany/Sandbox/TestApplication
Version: 0.1.0-ci.33
MyCompany/Sandbox:TestApplication 0.1.0-ci.33 published!
```

Some quick debugging of version 2.2.3.9 shows that the hang happens here:
https://github.com/Inedo/Inedo.UPack/blob/master/src/Inedo.UPack/Net/DefaultApiTransport.cs#L51

**Comment by gdivis** [comment]
This should actually be fixed in 2.2.4 through the update of the Inedo.UPack NuGet package. In short, the 2.2.3 version was always trying to do a chunked upload, which does not appear to be processed correctly sometimes.
