### ISSUE TITLE
Upack should preserve case of actual package ID and group when registering

### ISSUE THREAD

**Issue by wldevries** [Inedo/upack#50]
The package group and name that upack registers is the id you pass in via the command line. The problem is that it searches for the package without matching casing of characters.

From the _Manifest Specification_ and _Package Identification_ manual pages it is unclear whether a package identifier is supposed to be case insensitive.

**Steps to reproduce**
* Publish a package with group "InstructionVideos" and name "Lunges"
* Install the package using the following command line:
`upack install instructionvideo/lunges --source=http://myserver/upack/Content/ --user=user:password --target=c:\destination`

**Expected result**
It registers the package as `InstructionVideo/Lunges`

**Actual result**
The package is registered as `instructionvideo/lunges`. Here follows the entry from `installedPackages.json`:

```
  {
    "group": "instructionvideo",
    "name": "lunges",
    "version": "1.0.0",
    "path": "c:\\destination",
    "feedUrl": "http://myserver/upack/Content/",
    "installationDate": "2019-01-10T18:24:32.1665697+01:00",
    "installedUsing": "upack/2.2.2.2",
    "installedBy": "user"
  }
```

**Version used**
Upack version 2.2.2.2

**Comment by gdivis** [comment]
The specification should include that package groups/ids are case insensitive. However, it looks like upack.exe is just using whatever value is supplied as the argument rather than whatever casing is in the _actual_ package's metadata. We'll fix that so it records the actual casing in the package registry.
