### ISSUE TITLE
Missing uninstall / update commands

### ISSUE THREAD

**Issue by FabianTe** [Inedo/upack#57]
I am really missing an uninstall command that removes all installed files and then de-registeres the pkg in the local registry.

Edit: I figured, that I am equally confused why there is no update functionality.

Also a side note: I notice the tool is implemented in C# *and* Go. Why? Which build is currently distributed and why?

**Comment by apxltd** [comment]
Hello; sorry on the slow response, we just aren't getting notices of these, despite watching :/

Use the C# version, generally speaking.

The Go version was made prior to dotnetcore, and may be deprecated; it also serves as a reference implementation.

**Comment by nokinger** [comment]
Hi, is there any status update for this issue?

**Comment by apxltd** [comment]
I'm afraid it's not on our priority list at the moment, but we definitely welcome pull-requests or other help!
