### ISSUE TITLE
Add cross-platform builds to releases / downloads

### ISSUE THREAD

**Issue by tknerr** [Inedo/upack#61]
The documentation at  https://inedo.com/upack says:

> Package your applications and components directly from the Visual Studio Extension or the Jenkins Plug-in, or using free and open-source tools including the Universal Package Explorer or **the cross-platform** UPack Command-line Interface.

However, looking through the docs I could not find any way to install `upack` on any system other than windows:

* the only published binary is `upack.exe` for  windows, but there are no linux or macOS binaries published in the releases for this repo.
* the only package installation method mentioned in the docs is via chocolatey, which is also windows only

Looking at the source code, I assume that `upack` is a golang application, so it would be only a matter of building and publishing the cross-platform builds?

Or are the docs wrong and there is currently no cross-platform CLI available?

**Comment by rhessinger** [comment]
@tknerr This is actually written in C#, the go version was a test that we decided not to continue with.  I will be working to get a net core 3.1 release out early next week that I verified works Ubuntu 18.04 and Windows 10.  I will reply to this Issue as soon as I have pushed this release.  Sorry about the confusion, but thank you very much for bringing this to our attention!

**Comment by p418** [comment]
@tknerr 

I'm not a C# guy but managed to build docker alpine linux based image to use within my gitlab's pipelines.

Maybe it could help you build your own binary

```Dockerfile
ARG BUILD_VERSION

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine as BUILD
ARG BUILD_VERSION

WORKDIR /source
RUN apk add --no-cache git
RUN git clone -b upack-${BUILD_VERSION} https://github.com/Inedo/upack.git .
WORKDIR /source/src/dotnet
RUN sed -i 's/netcoreapp2\.0/netcoreapp3.1/' upack/upack.csproj
RUN dotnet publish \
    -c release \
    -p:PublishSingleFile=true \
    -p:PublishTrimmed=true \
    --runtime linux-musl-x64 \
    --framework netcoreapp3.1 \
    -p:Version=${BUILD_VERSION} \
    -o /app

FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.1-alpine
ARG BUILD_VERSION
ENV UPACK_VERSION $BUILD_VERSION

COPY --from=BUILD /app/upack /usr/bin/


CMD ["upack"]
```

**Comment by rhessinger** [comment]
Hi @tknerr,

I have uploaded a new upack release to our Git Hub Releases page that includes a .NET core version.  I have also updated the readme file to include how to run this with .NET Core.  You'll need to use the .NET Core version on linux or MacOS.  Please comment back if you have any issues!

**Comment by tknerr** [comment]
Hi @rhessinger,

sorry for the late response. I just wanted to confirm that this is working as expected now, thanks a lot!! 👍 

I added `alias upack="dotnet /path/to/upack.dll"` and it feels exactly like the native command now :)

Cheers, Torben

**Comment by rhessinger** [comment]
@tknerr That is great to hear!
