### ISSUE TITLE
Prerelease version field is not included in output file name during pack

### ISSUE THREAD

**Issue by F4NJGKQ** [Inedo/upack#77]
upack pack "C:\Portal"  --manifest="C:\PortalMin.upack.json"  --targetDirectory="C:\portal\artifacts" 

Content of Json:
{"name": "Portal","version": "1.0.0-dev","title": "Portal"}

Output:
Portal-1.0.0.upack (I was expecting Portal-1.0.0-dev.upack)

**Comment by gdivis** [comment]
`1.0.0-dev` is a perfectly valid version number; this is a bug. We'll publish upack v3.1.2 soon to fix this. Thanks for reporting the issue!

**Comment by gdivis** [comment]
Ah, sorry. I misread your question. Yes, version must be x.x.x format, as upack files require [semver2](https://semver.org/) versioning.

**Comment by F4NJGKQ** [comment]
So, now when 3.1.2 version is released, I should be able to get it to churn out 1.0.0-dev.upack. Right?

**Comment by gdivis** [comment]
Correct. Actually, from my testing it still created a package with 1.0.0-dev in its manifest, but the default file name was wrong. For now, you could work around by just renaming the output file.
