### ISSUE TITLE
Upack support for musl distributions

### ISSUE THREAD

**Issue by dmalanij** [Inedo/upack#79]
With the change introduced in version 3.1.0 to make `upack` cli available as a single executable, it's not possible to use it within the lighter Linux distributions. For instance, using the `mcr.microsoft.com/dotnet/runtime:6.0-alpine` image, once downloaded and extracted the file from the corresponding _-linux-x64.zip_ archive, you simply get:
```
/bin/sh: ./upack not found
```

I guess whatever way the files are being packaged is not a valid executable format for the case of _musl_ distributions. However, the cli in its version **3.0** that included all the binaries, worked fine (using the `dotnet upack.dll` to run, of course).

I'm not asking to get a specific bundle for this scenario, but it would be appreciated to keep the old _multipurposed_ package that is suitable to most (if not all) OS.

**Comment by gdivis** [comment]
Hi @dmalanij 

You're right, we should have also published a -musl archive. Going forward, we'll do that and also bring back the general-purpose binary that requires dotnet.

I don't know if it's suitable for your environment, but we are still distributing the fully cross platform version as a dotnet tool, which you should be able to install from that dotnet runtime image. You can use `dotnet tool install upack -g` and then run it as `dotnet upack`, and it should work on alpine.

**Comment by dmalanij** [comment]
Thanks for your reply, @gdivis and sorry for not coming back to you earlier.

I know about the option for installing it through `dotnet tool` but the image I'm working on is based on the runtime, not the _sdk_ so that's not an option. I could try a workaround with a multistage installing the tool and then copying the binaries to the target runtime only image, but at that point I can live with version 3.0.0 for now. 

Not offering myself to prepare a MR with the change as my time for such initiatives is quite limited right now (and as far as I could see, no details on how binaries are being produced and packaged is available on the public repo).

Cheers

**Comment by gdivis** [comment]
No worries. I've actually planned to get the musl and general versions out by the end of the week. It's just a matter of updating our build script a deploying a new release.

**Comment by gdivis** [comment]
This has now been deployed in v3.1.3.
